name: seabattle_app
description: An conduit application with a database connection and data model.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  conduit: ^5.1.5
  conduit_core: ^5.1.5
  conduit_postgresql: ^5.1.5

dev_dependencies:
  test: ^1.21.6
  conduit_test: ^5.1.5
